# Generated by Django 2.2.5 on 2019-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teltype', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('questiontype', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'userback',
                'managed': True,
            },
        ),
    ]
