# Generated by Django 2.2.5 on 2019-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userback',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
